import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google"; // гугл шрифты
import "./globals.css";
import { Header } from "@/widgets/header/Header";
import { Footer } from "@/widgets/footer/Footer";
import { AuthModalProvider } from "./shared/providers/AuthModalProvider";




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
    >
      <body className="  ">

        <AuthModalProvider>
          <Header />

          <main  >

            {children}

          </main>
        </AuthModalProvider>

        < Footer />
      </body>
    </html >
  );
}
